![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [2]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.21.4


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [9]:
z = np.zeros(10)

In [10]:
#np.array([0] * 10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
z.size

10

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [13]:
z= np.arange(10,50)

In [14]:
z.size

40

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [19]:
np.ones([2,2], dtype=float)


array([[1., 1.],
       [1., 1.]])

In [20]:
np.ones([2,2], dtype=int)

array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [21]:
np.ones([3,2], dtype=float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
np.ones([3,2], dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
np.arange(2,3,0.2)

array([2. , 2.2, 2.4, 2.6, 2.8])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [5]:
x = np.arange(5, dtype=int)

np.ones_like(x)


array([1, 1, 1, 1, 1])

In [36]:
X = np.arange(4, dtype=int)

np.ones_like(X)

array([1, 1, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [47]:
x = np.random.randint(1000000, size=(2,2))
print (x)

np.zeros_like(x)


[[561508 546538]
 [682157 915118]]


array([[0, 0],
       [0, 0]])

In [48]:
X = np.array([[1,2,3], [4,5,6]], dtype=int)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [57]:
np.ones([4,4])*5


array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.ones([4,4], dtype=np.int) * 5

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [60]:
x = np.ones([5,5])

np.ones_like(x)*7

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [ ]:
X = np.array([[2,3], [6,2]], dtype=np.int)

np.ones_like(X) * 7

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [66]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
#np.eye(3)
np.identity(3)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [70]:
np.random.randint(10, size=[2,2])


array([[8, 4],
       [4, 3]])

In [76]:
np.random.randn(2,2,2)

array([[[ 1.10545591, -0.7093685 ],
        [-0.17095417, -0.01739681]],

       [[-1.16332218,  2.48261044],
        [ 0.96921035, -0.59138975]]])

In [68]:
np.random.randint(10, size=3)

array([8, 9, 2])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [84]:
np.random.randn(3,3,3)

array([[[-1.10268567, -0.72869633,  1.04916104],
        [-0.49229259,  0.31590536, -2.03755032],
        [ 1.27545649, -1.03779117, -0.55965817]],

       [[ 0.75806785,  0.57817711,  1.83820285],
        [ 0.30126768,  0.17517384,  0.79915878],
        [-0.49037634, -0.09945609, -1.69572879]],

       [[ 0.53187975, -0.19785705, -1.14838637],
        [-0.15607011,  0.18721875, -0.28017709],
        [-0.94493424, -0.86325314, -0.57100347]]])

In [79]:
#np.random.random((3,3,3)) 
np.random.randn(3,3,3) # 0 to 1 floats

array([[[ 1.05442349,  0.82404247,  0.5695549 ],
        [ 0.9574816 ,  0.28114278, -0.01084662],
        [-0.80033459, -0.42942049,  0.42743215]],

       [[ 0.67892347, -0.57620759, -1.07591038],
        [-0.21033183,  1.56003096,  0.81319942],
        [-0.67100488,  0.06947743,  0.28931595]],

       [[ 1.14762508, -0.65554192, -0.3741478 ],
        [-1.12317335,  0.69444592,  0.2463975 ],
        [-0.74416211,  1.98710901,  1.52848212]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [91]:
x = [[1,2,3,4],[1,2,3]]
print (x)
y = np.array(x)
print (y)



[[1, 2, 3, 4], [1, 2, 3]]
[list([1, 2, 3, 4]) list([1, 2, 3])]


/var/folders/h2/hb53gmnj4j5_s7xj600zbycc0000gn/T/ipykernel_1708/3171543526.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  y = np.array(x)


In [85]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [92]:
x = np.array([1,2,3])
y=np.copy(x)
print (y)

[1 2 3]


In [94]:
X = np.array([5,2,3], dtype=int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 4576421104
[5 2 3] 4572702224


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [101]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 11)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [103]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1, 11, 2)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [127]:
np.arange(1,11)[11::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [108]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [116]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [145]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [136]:
z = np.zeros ((10,10))
print (z)
print ("%d bytes" % (z.size * z.itemsize))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
800 bytes


In [137]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [150]:
x = np.arange(1,2,3)
x[0]


1

In [151]:
X = np.array(['A','B','C','D','E'])

X[0]

'A'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [167]:
x = np.random.randint(10, size=[1,3])

print (x)

print (x[0,-1])

[[4 5 1]]
1


In [ ]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [169]:
x = np.array ([1,2,3,4,5,6])
x[:3]

array([1, 2, 3])

In [ ]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [174]:
x = np.array([1,2,3,4,5,6])
x[1:-1]


array([2, 3, 4, 5])

In [170]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [178]:
x = np.array([1,2,3,4,5,6])
print (x)
x[4:2:-1]


[1 2 3 4 5 6]


array([5, 4])

In [ ]:
X = np.array(['A','B','C','D','E'])

X[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [184]:
x = np.arange(10)
print (x)
x[1::2]

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

In [ ]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [189]:
x = np.arange(100).reshape(10,10)
print (x)
print (x[0])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [190]:
x = np.arange(100).reshape(10,10)
print (x)
print (x[-1])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[90 91 92 93 94 95 96 97 98 99]


In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [191]:
x = np.arange(100).reshape(10,10)
print (x)
print (x[0][0])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
0


In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [193]:
x = np.arange(100).reshape(10,10)
print (x)
print (x[-1][-1])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
99


In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [205]:
x = np.arange(16).reshape(4,4)
print (x)
print (x[1:-1,1:-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  6]
 [ 9 10]]


In [194]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [208]:
x = np.arange(16).reshape(4,4)
print (x)
print (x[:2,:2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [4 5]]


In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [210]:
x = np.arange(16).reshape(4,4)
print (x)
print (x[-2:,-2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[10 11]
 [14 15]]


In [211]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [222]:
x = np.arange(1,11)
print (x)
np.array(x,np.float16)

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float16)

In [ ]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [223]:
x = np.arange(1,11)

x [::-1]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [224]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [243]:
x = np.random.randint(10, size=(1,4))

x.sort()
x


array([[1, 7, 8, 9]])

In [ ]:
X = [0, 10, -5, 40, -3]

X.sort()
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [250]:
x = np.random.randint(10, size=(10))

x[:4]=1
x

array([1, 1, 1, 1, 3, 7, 2, 8, 5, 1])

In [ ]:
X = np.zeros(10)

X[4] = 1
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [ ]:
# your code goes here


In [251]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [253]:
x = np.random.randint(10, size=(10,5))

x[-1]=5
x

array([[9, 9, 5, 4, 7],
       [4, 6, 6, 0, 5],
       [9, 7, 1, 0, 9],
       [0, 9, 4, 7, 7],
       [5, 5, 1, 9, 3],
       [7, 6, 4, 6, 4],
       [8, 3, 5, 4, 1],
       [6, 0, 3, 0, 3],
       [5, 2, 4, 4, 0],
       [5, 5, 5, 5, 5]])

In [254]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [ ]:
# your code goes here


In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [257]:
x = np.random.randint(10, size=(10))

print (x)

print (x +5)

[2 9 0 6 4 8 2 4 4 7]
[ 7 14  5 11  9 13  7  9  9 12]


In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [267]:
x = np.random.randint(-5,10, size=(10))

print (x)

print (x<=0)

[ 5  6  8  5 -2  0  8  3  6  8]
[False False False False  True  True False False False False]


In [264]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [269]:
x = np.random.randint(-5,10, size=(10))

print (x)

print (x[x<0])

[-2  5  9 -2  8  8 -4 -4 -5  3]
[-2 -2 -4 -4 -5]


In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [271]:
x = np.random.randint(-5,10, size=(10))

print (x)

print (x[x>5])

[ 1  8  1  0 -4  4  6 -1 -3  3]
[8 6]


In [272]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [277]:
x = np.random.randint(-5,10, size=(10))

print (x)
print (x.mean())

print (x[x>x.mean()])

[-4  6  0  9  2  0  6 -3  4 -1]
1.9
[6 9 2 6 4]


In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [317]:
x = np.random.randint(-5,10, size=(10))

print (x)
print (x.mean())

print (x[(x == 2) | (x == 10)])

[ 2  3 -2  7  5  1  1  6  7 -2]
2.8
[2]


In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [335]:
x = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

x.all()



False

In [329]:
np.zeros((2, 2), dtype=bool)

array([[False, False],
       [False, False]])

In [327]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [ ]:
# your code goes here


In [322]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [336]:
x = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

x.sum()

43

In [337]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

43

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [339]:
x = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

x.mean()

4.777777777777778

In [340]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

3.7

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [343]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0)

array([28, 32, 36, 40])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [349]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=0)

array([ 7.,  8.,  9., 10.])

In [346]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [ ]:
# your code goes here


In [ ]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)